[/Script/DriveableVehiclePack51.Config]
NetEnable=True    ;是否启用网络

ServerIP=192.1.10.80

AiIP=127.0.0.1
AiPort=20005

LocalIp = 192.1.10.80
LocalPort = 20003
AIDedicatedPort = 20001

GroupLeaderIP = 192.1.10.80
GroupLeaderPort = 20003

MapLatitude=(("Openworld_10K", (X=42.989400,Y=113.808900,Z=0.000000)),("PingYuan_Tile", (X=-23.365600,Y=132.117100,Z=0.000000)),("Qiuling_Tile", (X=-38.011000,Y=-80.787300,Z=0.000000)))

;是否接收网络指令加载车辆信息
NetLoad = True 

;Hard_client 带有硬件的客户端，不接受 NetLoad，限制只能加载99A和F1，
;20_client   20个节点的客户端 
;UAV_client  无人机客户端
;3D_client   三维台式客户端  ，不接受 NetLoad，
;AI_client   AI节点        ，不接受 NetLoad，  --准备废弃
ClientType = "3D_client"

SeatType=21   ; 11-99ADriver  || 12-99AGunner    ||  13-Control || 21-F1Driver  || 22 - F1Gunner  || 99-99A全车(20节点客户端生效)  ||  99-F1全车 (20节点客户端生效)(删除这快) || 50~53 无人机 1~4 

Camp = 4       ; 1 - 蓝色集团军  ||  2 - 红色集团军  ||   3 - AI       ||   4 - 三维态势     ||
Number = 1     ; 坦克编号 序号从1开始 相同阵营的编号禁止重复！  5-99A       ||   三维态势设置为 1  
 
EnableUp = true       ; 是否启用上传数据
UploadInterval = 1    ; 上传间隔

IsTest = True; 是否测试模式
LoadPosX = 348160.0 ;722823      ;加载位置X   --仅测试使用--
LoadPosY = 258350.0 ;192584      ;加载位置Y   --仅测试使用--
roomID = 1                  ;加载房间号  --仅测试使用--     ||  1 ~ 5
MapName = "PingYuan_Tile"    ;加载地图    --仅测试使用--     ||  PingYuan_Tile | Qiuling_Tile | Openworld_10K
ControlMode = 1             ;控制方式    --仅测试使用--     ||  1- 键鼠  2- 实装  3 -智能体  4 - AI

Nodes01_Camp = 10       ; 10 - 蓝色集团军  ||  20 - 红色集团军  
Nodes01_Number = 11
Nodes01_PositionX = 331120.0
Nodes01_PositionY = 281710.0
Nodes01_Item = "F1Create"        ;F1Create、A99Create、UAV_1、UAV_2、UAV_3、UAV_4

Nodes02_Camp = 10       ; 10 - 蓝色集团军  ||  20 - 红色集团军
Nodes02_Number = 12
Nodes02_PositionX = 331120.0
Nodes02_PositionY = 281040.0
Nodes02_Item = "F1Create"       

Nodes03_Camp = 10       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes03_Number = 13
Nodes03_PositionX = 330910.0
Nodes03_PositionY = 279880.0
Nodes03_Item = "F1Create" 

Nodes04_Camp = 10       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes04_Number = 14
Nodes04_PositionX = 330770.0
Nodes04_PositionY = 278850.0
Nodes04_Item = "F1Create" 

Nodes05_Camp = 10       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes05_Number = 15
Nodes05_PositionX = 330570.0
Nodes05_PositionY = 277380.0
Nodes05_Item = "F1Create" 

Nodes06_Camp = 10       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes06_Number = 16
Nodes06_PositionX = 330340.0
Nodes06_PositionY = 275940.0
Nodes06_Item = "F1Create" 

Nodes07_Camp = 10       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes07_Number = 17
Nodes07_PositionX = 330200.0
Nodes07_PositionY = 274390.0
Nodes07_Item = "F1Create" 

Nodes08_Camp = 10      ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes08_Number = 18
Nodes08_PositionX = 329920.0
Nodes08_PositionY = 272190.0
Nodes08_Item = "F1Create" 

Nodes09_Camp = 10      ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes09_Number = 19
Nodes09_PositionX = 329800.0
Nodes09_PositionY = 270210.0
Nodes09_Item = "F1Create"

Nodes10_Camp = 10       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes10_Number = 20
Nodes10_PositionX = 329490.0
Nodes10_PositionY = 267820.0
Nodes10_Item = "F1Create"

Nodes11_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes11_Number = 11
Nodes11_PositionX = 329270.0
Nodes11_PositionY = 265460.0
Nodes11_Item = "F1Create"

Nodes12_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes12_Number = 12
Nodes12_PositionX = 329020.0
Nodes12_PositionY = 262450.0
Nodes12_Item = "F1Create"

Nodes13_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes13_Number = 13
Nodes13_PositionX = 328740.0
Nodes13_PositionY = 259740.0
Nodes13_Item = "F1Create"

Nodes14_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes14_Number = 14
Nodes14_PositionX = 328840.0
Nodes14_PositionY = 257060.0
Nodes14_Item = "F1Create"

Nodes15_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes15_Number = 15
Nodes15_PositionX = 329900.0
Nodes15_PositionY = 255840.0
Nodes15_Item = "F1Create"

Nodes16_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes16_Number = 16
Nodes16_PositionX = 331590.0
Nodes16_PositionY = 256190.0
Nodes16_Item = "F1Create"

Nodes17_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes17_Number = 17
Nodes17_PositionX = 333410.0
Nodes17_PositionY = 256250.0
Nodes17_Item = "F1Create"

Nodes18_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes18_Number = 18
Nodes18_PositionX = 334990.0
Nodes18_PositionY = 256510.0
Nodes18_Item = "F1Create"

Nodes19_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes19_Number = 19
Nodes19_PositionX = 336790.0
Nodes19_PositionY = 256780.0
Nodes19_Item = "F1Create"

Nodes20_Camp = 20       ; 1 - 蓝色集团军  ||  2 - 红色集团军
Nodes20_Number = 20
Nodes20_PositionX = 330570.0; 339730.0
Nodes20_PositionY = 278380.0; 256990.0
Nodes20_Item = "F1Create"

VideoPath = "D:\Work\feiQ\feiq\Recv Files\\UE_5.3\Engine\Binaries\Win64\DDATest_0.h264"

